import Head from 'next/head'
import Script from 'next/script'
import Footer from '../components/Footer/Footer'
import Hero from '../components/Hero/Hero'
import Intro from '../components/Intro/Intro'
import Personnel from '../components/Personnel/Personnel'
import Popular from '../components/Popular/Popular'
import Reservation from '../components/Reservation/Reservation'
import Sidebar from '../components/Sidebar/Sidebar'
import Strength from '../components/Strengths/Strength'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Moe Restoran | Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
	      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Hero />
      <Intro />
      <Popular />
      <Strength />
      <Reservation />
      <Personnel />
      <Footer />
      <Script src='https://kit.fontawesome.com/4ef8c63dd7.js' />
    </div>
  )
}
